version: '3.8'

services:
  db:
    image: postgres:16
      #healthcheck:
      #test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      #interval: 5s
      #timeout: 5s
      #retries: 5
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env.db
    networks:
      - mynetwork

  backend:
    build: .
    command: >
      bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python create_superuser.py &&
      gunicorn transcendence.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./media:/usr/media
    expose:
      - 8000
    env_file:
      - .env.db
      - .env.backend
    depends_on:
      - db
      #db:
        #condition: service_healthy
    networks:
      - mynetwork
  
  nginx:
    build: ./nginx
    ports:
      - "8443:8443"
    volumes:
      - ./nginx/frontend:/usr/share/nginx/html
      - ./media:/www/media
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
 mynetwork:

volumes:
 dbdata:
 static_volume:
